### ISSUE TITLE
I can't sign out of Deri Kurniawan's account and sign into mine

### ISSUE THREAD

**Issue by ask-arim** [Deri-Kurniawan/Deri-Kurniawan.github.io#17]
Can you please change [the website](https://deri-kurniawan.vercel.app) so that I can sign out of your account and sign in to my account instead of yours?

**Comment by Deri-Kurniawan** [comment]
Because the purpose of this application is my own Windows 11 Desktop, so it will be very much information about me, but you can clone it and change the data with your data
